<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Buffer_Layout_Set_String_Array" Id="{cf0ddbea-b9b2-44af-9e2f-56dfedf2d1b5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Buffer_Layout_Set_String_Array : UINT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Buffer_Layout_Set_String_Array">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>