<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Buffer_Layout_Set_USInt_Array" Id="{37bfa2a9-e120-4901-b10b-08a05e13ad83}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Buffer_Layout_Set_USInt_Array : UINT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Buffer_Layout_Set_USInt_Array">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>