<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Buffer_Layout_Set_UDInt_Array" Id="{4da5b8ee-4a07-412a-b657-ec8182f244ae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Buffer_Layout_Set_UDInt_Array : UINT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Buffer_Layout_Set_UDInt_Array">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>