<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{ac7ccafc-0f66-4244-bca1-474ce436e2ea}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Layout : Buffer_Layout;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>