<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="RFID_Sensor_Read" Id="{d94d988c-3c6b-42c5-8f25-763312f3cffc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RFID_Sensor_Read : bool
VAR_INPUT
	Sensor : REFERENCE TO RFID_Sensor;
	P : UINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RFID_Sensor_Read">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>