<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Camera_Init" Id="{a70b5ab6-a358-4ede-ad88-10f3494b78fb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Camera_Init : BOOL
VAR_INPUT
	Camera : REFERENCE TO Cognex_Camera;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Camera.Acquistion.TriggerEnabel := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="Camera_Init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>