<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Camera_Set_Ouput_Layout" Id="{f5de775a-8f45-4d98-a894-f355d5c529da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Camera_Set_Ouput_Layout : UINT
VAR_INPUT
	Layout : Buffer_Layout;
END_VAR
VAR_IN_OUT
	Camera : Cognex_Camera;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Camera.Ouput_Buffer_Layout := Layout;]]></ST>
    </Implementation>
    <LineIds Name="Camera_Set_Ouput_Layout">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>