<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Camera_Load_Job" Id="{548e7354-7c81-4e98-a425-bdafd56ffdd3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Camera_Load_Job : BOOL
VAR_INPUT
	JobeBame : STRING[63];
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Camera_Load_Job">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>