<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Set_Bool_Fom_Buffer" Id="{340d57b3-98c1-48b8-8fe5-c9394811b3da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Set_Bool_Fom_Buffer : Buffer_Error
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Set_Bool_Fom_Buffer">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>