<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Set_String_From_Buffer" Id="{09ecb032-daa4-4318-a8a8-a42971dd2e79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Set_String_From_Buffer : Buffer_Error
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Set_String_From_Buffer">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>